
import java.awt.Color;
import java.awt.Cursor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Melthon
 */
public class Game extends javax.swing.JFrame {
    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        CodePanel.setVisible(false);
        CodePanel.setEnabled(false);
        
        ShopBtn.setBorder(null);
        ActivityTab.setBorder(null);
        RegName.setVisible(false);
        ContinueBtn.setVisible(false);
        ContinueBtn.setEnabled(false);
        
        CodeBtn.setVisible(false);
        CodeBtn.setEnabled(false);
        
        ShopBtn.setVisible(false);
        AccBtn.setVisible(false);
        GamesBtn.setVisible(false);
        BedBtn.setVisible(false);
        EatBtn.setVisible(false);
        BathBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CodePanel = new javax.swing.JPanel();
        claimBtn = new javax.swing.JButton();
        codeInput = new javax.swing.JTextField();
        CodeBg = new javax.swing.JLabel();
        CodeBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        PlayBtn = new javax.swing.JButton();
        MainMenuBg = new javax.swing.JLabel();
        RegName = new javax.swing.JTextField();
        ContinueBtn = new javax.swing.JButton();
        DogOpt = new javax.swing.JButton();
        CatOpt = new javax.swing.JButton();
        OptBg = new javax.swing.JLabel();
        ActivityTab = new javax.swing.JPanel();
        Tab = new javax.swing.JLabel();
        BathBtn = new javax.swing.JButton();
        EatBtn = new javax.swing.JButton();
        BedBtn = new javax.swing.JButton();
        GamesBtn = new javax.swing.JButton();
        AccBtn = new javax.swing.JButton();
        ShopBtn = new javax.swing.JButton();
        GameBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CodePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CodePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        claimBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/claimBtn.png"))); // NOI18N
        claimBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claimBtnActionPerformed(evt);
            }
        });
        CodePanel.add(claimBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 310, 60));

        codeInput.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CodePanel.add(codeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 320, 60));

        CodeBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeBg.png"))); // NOI18N
        CodePanel.add(CodeBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 270));

        getContentPane().add(CodePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 550, 270));

        CodeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/codeBtn.png"))); // NOI18N
        CodeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CodeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CodeBtnMouseExited(evt);
            }
        });
        CodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CodeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 90, 90));

        CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/closeBtn.png"))); // NOI18N
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseBtnMouseExited(evt);
            }
        });
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 90, 90));

        PlayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play.jpg"))); // NOI18N
        PlayBtn.setDisabledIcon(null);
        PlayBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PlayBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PlayBtnMouseExited(evt);
            }
        });
        PlayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PlayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 330, 110));

        MainMenuBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainmenu.jpg"))); // NOI18N
        getContentPane().add(MainMenuBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 1340));

        RegName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(RegName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 850, 360, 80));

        ContinueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/option/continueBtn.png"))); // NOI18N
        ContinueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContinueBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContinueBtnMouseExited(evt);
            }
        });
        ContinueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ContinueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 960, 350, 70));

        DogOpt.setBackground(new java.awt.Color(97, 107, 129));
        DogOpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/option/DogBorder.png"))); // NOI18N
        DogOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DogOptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DogOptMouseExited(evt);
            }
        });
        DogOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DogOptActionPerformed(evt);
            }
        });
        getContentPane().add(DogOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 290, 250));

        CatOpt.setBackground(new java.awt.Color(97, 107, 129));
        CatOpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/option/CatBorder.png"))); // NOI18N
        CatOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CatOptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CatOptMouseExited(evt);
            }
        });
        CatOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatOptActionPerformed(evt);
            }
        });
        getContentPane().add(CatOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 290, 250));

        OptBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/option/bgOpt.png"))); // NOI18N
        getContentPane().add(OptBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 1340));

        ActivityTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tab.setBackground(new java.awt.Color(14, 5, 39));
        Tab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/tab.png"))); // NOI18N
        ActivityTab.add(Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        getContentPane().add(ActivityTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1010, 770, 200));

        BathBtn.setBackground(new java.awt.Color(255, 255, 255));
        BathBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/bathBtn.png"))); // NOI18N
        BathBtn.setBorderPainted(false);
        BathBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BathBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BathBtnMouseExited(evt);
            }
        });
        BathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BathBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BathBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1210, 120, 120));

        EatBtn.setBackground(new java.awt.Color(255, 255, 255));
        EatBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/eatbtn.png"))); // NOI18N
        EatBtn.setBorderPainted(false);
        EatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EatBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EatBtnMouseExited(evt);
            }
        });
        EatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EatBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EatBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 1210, 120, 120));

        BedBtn.setBackground(new java.awt.Color(255, 255, 255));
        BedBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/bedBtn.png"))); // NOI18N
        BedBtn.setBorderPainted(false);
        BedBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BedBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BedBtnMouseExited(evt);
            }
        });
        BedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BedBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1210, 120, 120));

        GamesBtn.setBackground(new java.awt.Color(255, 255, 255));
        GamesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/gameBtn.png"))); // NOI18N
        GamesBtn.setBorderPainted(false);
        GamesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GamesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GamesBtnMouseExited(evt);
            }
        });
        GamesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GamesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(GamesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1210, 120, 120));

        AccBtn.setBackground(new java.awt.Color(255, 255, 255));
        AccBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/accBtn.png"))); // NOI18N
        AccBtn.setBorderPainted(false);
        AccBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccBtnMouseExited(evt);
            }
        });
        AccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1210, 120, 120));

        ShopBtn.setBackground(new java.awt.Color(255, 255, 255));
        ShopBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/shopBtn.png"))); // NOI18N
        ShopBtn.setBorderPainted(false);
        ShopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ShopBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ShopBtnMouseExited(evt);
            }
        });
        ShopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShopBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ShopBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1210, 120, 120));

        GameBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameBg.png"))); // NOI18N
        getContentPane().add(GameBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 1340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayBtnActionPerformed
 
        MainMenuBg.setVisible(false);
        PlayBtn.setVisible(false);
    }//GEN-LAST:event_PlayBtnActionPerformed

    private void PlayBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayBtnMouseEntered
        PlayBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_PlayBtnMouseEntered

    private void PlayBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayBtnMouseExited
        PlayBtn.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_PlayBtnMouseExited

    private void CatOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatOptActionPerformed
        DogOpt.setBackground(Color.decode("#616b81"));
        CatOpt.setBackground(Color.decode("#ffffff"));
        OptBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/option/nameOpt.png")));
        RegName.setVisible(true);
        ContinueBtn.setVisible(true);
        ContinueBtn.setEnabled(true);
    }//GEN-LAST:event_CatOptActionPerformed

    private void DogOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DogOptActionPerformed
        CatOpt.setBackground(Color.decode("#616b81"));
        DogOpt.setBackground(Color.decode("#ffffff"));
        OptBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/option/nameOpt.png")));
        RegName.setVisible(true);
        ContinueBtn.setVisible(true);
        ContinueBtn.setEnabled(true);
    }//GEN-LAST:event_DogOptActionPerformed

    private void DogOptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DogOptMouseEntered
        DogOpt.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_DogOptMouseEntered

    private void DogOptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DogOptMouseExited
        DogOpt.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_DogOptMouseExited

    private void CatOptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatOptMouseEntered
        CatOpt.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CatOptMouseEntered

    private void CatOptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatOptMouseExited
        CatOpt.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_CatOptMouseExited

    private void ContinueBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueBtnMouseEntered
        ContinueBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ContinueBtnMouseEntered

    private void ContinueBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueBtnMouseExited

    }//GEN-LAST:event_ContinueBtnMouseExited

    private void ContinueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueBtnActionPerformed
        String playerName = RegName.getText();
        if(!playerName.isEmpty()) { 
            CodeBtn.setVisible(true);
            CodeBtn.setEnabled(true);
            
            MainMenuBg.setVisible(false);
            MainMenuBg.setEnabled(false);

            PlayBtn.setVisible(false);
            RegName.setVisible(false);
            ContinueBtn.setVisible(false);

            OptBg.setVisible(false);
            OptBg.setEnabled(false);
            DogOpt.setVisible(false);
            CatOpt.setVisible(false);

            ShopBtn.setVisible(true);
            AccBtn.setVisible(true);
            GamesBtn.setVisible(true);
            BedBtn.setVisible(true);
            EatBtn.setVisible(true);
            BathBtn.setVisible(true);
        }
    }//GEN-LAST:event_ContinueBtnActionPerformed

    private void ShopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShopBtnActionPerformed
        ShopBtn.setBackground(Color.decode("#616b81"));
        AccBtn.setBackground(Color.decode("#ffffff"));
        GamesBtn.setBackground(Color.decode("#ffffff"));
        BedBtn.setBackground(Color.decode("#ffffff"));
        EatBtn.setBackground(Color.decode("#ffffff"));
        BathBtn.setBackground(Color.decode("#ffffff"));
    }//GEN-LAST:event_ShopBtnActionPerformed

    private void AccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccBtnActionPerformed
        ShopBtn.setBackground(Color.decode("#ffffff"));
        AccBtn.setBackground(Color.decode("#616b81"));
        GamesBtn.setBackground(Color.decode("#ffffff"));
        BedBtn.setBackground(Color.decode("#ffffff"));
        EatBtn.setBackground(Color.decode("#ffffff"));
        BathBtn.setBackground(Color.decode("#ffffff"));
    }//GEN-LAST:event_AccBtnActionPerformed

    private void GamesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamesBtnActionPerformed
        ShopBtn.setBackground(Color.decode("#ffffff"));
        AccBtn.setBackground(Color.decode("#ffffff"));
        GamesBtn.setBackground(Color.decode("#616b81"));
        BedBtn.setBackground(Color.decode("#ffffff"));
        EatBtn.setBackground(Color.decode("#ffffff"));
        BathBtn.setBackground(Color.decode("#ffffff"));
    }//GEN-LAST:event_GamesBtnActionPerformed

    private void BathBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BathBtnActionPerformed
        ShopBtn.setBackground(Color.decode("#ffffff"));
        AccBtn.setBackground(Color.decode("#ffffff"));
        GamesBtn.setBackground(Color.decode("#ffffff"));
        BedBtn.setBackground(Color.decode("#ffffff"));
        EatBtn.setBackground(Color.decode("#ffffff"));
        BathBtn.setBackground(Color.decode("#616b81"));
    }//GEN-LAST:event_BathBtnActionPerformed

    private void EatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EatBtnActionPerformed
        ShopBtn.setBackground(Color.decode("#ffffff"));
        AccBtn.setBackground(Color.decode("#ffffff"));
        GamesBtn.setBackground(Color.decode("#ffffff"));
        BedBtn.setBackground(Color.decode("#ffffff"));
        EatBtn.setBackground(Color.decode("#616b81"));
        BathBtn.setBackground(Color.decode("#ffffff"));
    }//GEN-LAST:event_EatBtnActionPerformed

    private void BedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BedBtnActionPerformed
        ShopBtn.setBackground(Color.decode("#ffffff"));
        AccBtn.setBackground(Color.decode("#ffffff"));
        GamesBtn.setBackground(Color.decode("#ffffff"));
        BedBtn.setBackground(Color.decode("#616b81"));
        EatBtn.setBackground(Color.decode("#ffffff"));
        BathBtn.setBackground(Color.decode("#ffffff"));
    }//GEN-LAST:event_BedBtnActionPerformed

    private void ShopBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShopBtnMouseEntered
        ShopBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ShopBtnMouseEntered

    private void ShopBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShopBtnMouseExited
        ShopBtn.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_ShopBtnMouseExited

    private void AccBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccBtnMouseEntered
        AccBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_AccBtnMouseEntered

    private void AccBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccBtnMouseExited
        AccBtn.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_AccBtnMouseExited

    private void GamesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GamesBtnMouseEntered
        GamesBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_GamesBtnMouseEntered

    private void GamesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GamesBtnMouseExited
        GamesBtn.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_GamesBtnMouseExited

    private void EatBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EatBtnMouseEntered
        EatBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_EatBtnMouseEntered

    private void BathBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BathBtnMouseEntered
        BathBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BathBtnMouseEntered

    private void BathBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BathBtnMouseExited
        BathBtn.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BathBtnMouseExited

    private void EatBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EatBtnMouseExited
        EatBtn.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_EatBtnMouseExited

    private void BedBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BedBtnMouseEntered
        BedBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BedBtnMouseEntered

    private void BedBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BedBtnMouseExited
        BedBtn.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BedBtnMouseExited

    private void CodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeBtnActionPerformed
        if (CodePanel.isVisible()) {
        CodePanel.setVisible(false);
        codeInput.setText("");
    } else {
        CodePanel.setVisible(true);
    }
    }//GEN-LAST:event_CodeBtnActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        dispose();
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void CloseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseEntered
        CloseBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CloseBtnMouseEntered

    private void CloseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseExited
        CloseBtn.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_CloseBtnMouseExited

    private void CodeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodeBtnMouseEntered
        CodeBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CodeBtnMouseEntered

    private void CodeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodeBtnMouseExited
        CodeBtn.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_CodeBtnMouseExited

    private void claimBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claimBtnActionPerformed
        String code = codeInput.getText().trim();
    
        if (code.equals("NIGGA")) {
            CodeBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("codeBg.png")));
            CodePanel.setVisible(false);
            codeInput.setText("");
        } else {
            CodeBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("WRONG.png")));
        }
    }//GEN-LAST:event_claimBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Game().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccBtn;
    private javax.swing.JPanel ActivityTab;
    private javax.swing.JButton BathBtn;
    private javax.swing.JButton BedBtn;
    private javax.swing.JButton CatOpt;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JLabel CodeBg;
    private javax.swing.JButton CodeBtn;
    private javax.swing.JPanel CodePanel;
    private javax.swing.JButton ContinueBtn;
    private javax.swing.JButton DogOpt;
    private javax.swing.JButton EatBtn;
    private javax.swing.JLabel GameBg;
    private javax.swing.JButton GamesBtn;
    private javax.swing.JLabel MainMenuBg;
    private javax.swing.JLabel OptBg;
    private javax.swing.JButton PlayBtn;
    private javax.swing.JTextField RegName;
    private javax.swing.JButton ShopBtn;
    private javax.swing.JLabel Tab;
    private javax.swing.JButton claimBtn;
    private javax.swing.JTextField codeInput;
    // End of variables declaration//GEN-END:variables

}
